//
// Created by dolev on 24/05/2020.
//
#include"doctest.h"
#include <iostream>
#include "DemoGame.hpp"
TEST_CASE("testSum"){
            CHECK(3+1==2+2); 
            CHECK(6-1==5); 
            CHECK(2==1+1); 
            CHECK(4+10==7*2); 
            CHECK(15-5==5+5); 
            CHECK(1==2-1);
            CHECK(2==3-1);
            CHECK(4.2-1.1==3.1);
            CHECK(2.0+0.5==2.5);
            CHECK(1.5==1.5);
            CHECK(8*2==16);
            CHECK(10==10);
};
TEST_CASE("testtrue"){
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true); 
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
            CHECK(true==true);
};
TEST_CASE("testfalse") {
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
            CHECK(false==false);
};
TEST_CASE("testletter"){
            CHECK(a==a);
            CHECK(b==b);
            CHECK(c==c);
            CHECK(d==d);
            CHECK(e==e);
            CHECK(f==f);
            CHECK(g==g);
            CHECK(h==h);
            CHECK(i==i);
            CHECK(j==j);
            CHECK(k==k);
            CHECK(l==l);
            CHECK(m==m);
            CHECK(n==n);
            CHECK(o==o);
            CHECK(p==p);
            CHECK(q==q);
            CHECK(r==r);
            CHECK(s==s);
            CHECK(t==t);
}; 
TEST_CASE("testZero"){
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);22

            CHECK(true==true); 
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
            CHECK(0==0);
};
